apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chat-app

resources:
- ../base
- gateway.yaml

secretGenerator:
- envs:
  - .env
  name: envfile
  type: Opaque
  options:
    disableNameSuffixHash: true

# todo: patch kratos arguments to use dev configuration

